### ISSUE TITLE
Does this package support linux

### ISSUE THREAD

**Issue by amiltonwong** [crizCraig/deepdrive#3]
Hi, @crizCraig ,

Does this package support linux?

**Comment by crizCraig** [comment]
Sorry it does not, but stay tuned!

On Tue, Nov 8, 2016 at 1:30 AM amiltonwong <notifications@github.com> wrote:

Hi, @crizCraig <https://github.com/crizCraig> ,

Does this package support linux?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/crizCraig/deepdrive/issues/3>, or mute the thread
